# Generated by Django 5.2 on 2025-05-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
